// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjmpfvtjivzhrrryfgkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbXBmdnRqaXZ6aHJycnlmZ2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjQyOTksImV4cCI6MjA2OTIwMDI5OX0.tNnU9s-OmdvGbB1z3W6oGZgoL_8gFW2I58gy5KIuP7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});